# GotToVote Config

country: "Mo√ßambique"
election_year: "2018"

registration_end_date: "26th January 2018"

api_key: "AIzaSyB7yJRhV-SiMV4q7JB8yJI8HEeorZsN6jI"
table_id: "1JZqEtS8wR1dSU-zwOcnpzW6ycfWxP-vjYI2PtEsc"

url: https://votar.ntatebda.com   # with the https protocol


google_analytics: 'UA-110579932-1'

url: 'votar.ntatenda.com'

# ------------------------------------------------------------------------------
# Jekyll Config

# Handling Reading
safe: true

# Conversion
highlighter: rouge

